 version: "3.7"

 services:
   main:
      container_name: main
      build:
        context: ./server
        target: development
      volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
      ports:
        - ${SERVER_PORT}:${SERVER_PORT}
        - 3000:3000
      command:
