version: 2
jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
      - image: circleci/mongodb:4.2.2
        environment:
          MONGO_USER: mongo
          MONGO_PASSWORD: mongo
          MONGO_DB: RoyalAfg

    working_directory: ~/repo

    steps:
      - checkout

      - cmd: cd server,

      - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:   

